### PR TITLE
Adds global average comparison to kc command

### LINKED ISSUE #18: Kc improvement to include comparison to global average banrate
I'd like to see how my bans are doing in comparison to the global average banrate, this gives me some form of comparison instead of just a number in the dark.

### PR DESCRIPTION
**Pull request by Ferrariic**

### CODE REVIEW

**Comment by Ferrariic** [comment]
This was tested live and it works.

**Comment by extreme4all** [comment]
invert the function `if not`
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L11

then do this
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L42

**Comment by extreme4all** [comment]
api returns json not text
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L15

**Comment by extreme4all** [comment]
avoid using try except
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L13

**Comment by extreme4all** [comment]
clear naming please
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L15

**Comment by extreme4all** [comment]
invert like
```
accuracy = ''
if not manual_reports == 0:
```

https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L28

**Comment by extreme4all** [comment]
move up, no reason to waste cpu
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L34

**Comment by extreme4all** [comment]
might want to split this in two lines, one with the calculation and one where you build an f string
https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/twitter_bot/Commands/kc.py#L32

**Pull request merged**
